services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: libraryuser
      POSTGRES_PASSWORD: librarypass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U libraryuser -d library" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  backend:
    image: ghcr.io/ladoijo/booklending:dev-latest
    container_name: backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: always
volumes:
  postgres_data: