services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: libraryuser
      POSTGRES_PASSWORD: librarypass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U libraryuser -d library" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: .
    container_name: backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always
volumes:
  postgres_data: